got_moves-api/auth_api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework.routers import DefaultRouter

from auth_api import views


router = DefaultRouter()
router.register("users", views.UserViewset)


urlpatterns = [
    url(r'^', include(router.urls)),
]

got_moves-api/got_moves/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login

from rest_framework.routers import DefaultRouter

from auth_api import urls as auth_api_urls
from main import views


router = DefaultRouter()
router.register("categories", views.MoveCategoryViewset)
router.register("classic_moves", views.ClassicMoveViewset)
router.register("classic_move_performances", views.ClassicMovePerformanceViewset)

urlpatterns = [
    url(r'^foo/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api/users/', include(auth_api_urls)),
    url(r'^api/classic_move_search', views.ClassicMoveFilterListView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

got_moves-api/main/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


DEFAULT_CATEGORY_NAMES = (
    "Fan",
    "Cut",
    "Spread",
    "Ariel",
    "Combination",
    "Spring",
    "Display",
)
RANK_TITLES = (
    "Ensign",
    "Lieutenant Junior Grade",
    "Lieutenant",
    "Captain",
    "Major",
    "Lieutenant Colonel",
    "Colonel",
    "Commander",
    "Rear Admiral",
    "Vice Admiral",
    "Admiral",
)


class HasAUser(models.Model):
    """
    Abstract class used to populate childern with a `user` field
    """
    class Meta:
        abstract, ordering = True, ("-id",)
    user = models.ForeignKey(User)


class DateCreatedAndUpdate(models.Model):
    """
    Abstract class used to populate childern with a `date_created` field
    """
    class Meta:
        abstract, ordering = True, ("-id",)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def time_past_since_creation(self):
        time = (timezone.now()-self.date_created)
        hours = time.seconds / 60 / 60
        weeks = time.days / 7
        return "Weeks: {weeks}, Days: {days}, Hours: {hours}, Seconds: {seconds}".format(
            days=time.days, seconds=time.seconds, weeks=weeks, hours=hours
        )


class Likeable(models.Model):
    """
    Abstract class that gives childern the capability to be `liked`.
    """
    class Meta:
        abstract = True
    likes = models.IntegerField(null=True, blank=True, default=0)


class Descriptable(models.Model):
    """
    Abstract class that gives childern a text description.
    """
    class Meta:
        abstract = True
    description = models.TextField(blank=True, null=True)


class Named(models.Model):
    """
    Abstract class used to populate children with a name.
    """
    class Meta:
        abstract = True
    name = models.CharField(max_length=250, null=False)


class UniquelyNamed(models.Model):
    """
    Abstract class used to populate children with a unique name.
    """
    class Meta:
        abstract = True
    name = models.CharField(max_length=250, null=False)

    def __str__(self):
        return "{}".format(self.name)


class MoveCategory(UniquelyNamed, DateCreatedAndUpdate, Descriptable):
    """
    Type of move.
    """
    class Meta:
        unique_together = ("name", "one_handed",)
        ordering = ("name",)
    one_handed = models.BooleanField(default=False)
    number_of_packets = models.PositiveIntegerField(null=True, blank=True)
    user_submitted = models.ForeignKey(User, null=True)

    def __str__(self):
        display = ""
        if self.name:
            if self.one_handed:
                display += "One Handed "
            else:
                display += "Two Handed "
            display += self.name
        return "{}".format(display)

    def display(self):
        return self.__str__()

    def detail_url(self):
        return "/move_category/{0}".format(self.id)


class Move(UniquelyNamed, Descriptable, DateCreatedAndUpdate, Likeable):
    """
    The parent class of ClassicMove and UserMove.
    """
    class Meta:
        abstract = True
    credits = models.CharField(max_length=400, null=True)
    category = models.ForeignKey("MoveCategory")
    estimated_creation_date = models.DateField(blank=True, null=True)
    # TODO: switch back after adding Users in.
    # submitted_by = models.ForeignKey(User)

    def date_display(self):
        if self.estimated_creation_date is None:
            return ""
        else: return self.estimated_creation_date

    def category_detail_url(self):
        return self.category.detail_url()

    def category_display(self):
        return self.category.display()


class ClassicMove(Move):
    """
    This is a Classic Cardistry move that is practiced by many
    cardists around the world. It is noted as being ground
    breaking and having a heavy influence on the art as a whole.
    """
    pass


class UserMove(Move):
    """
    User submitted Move. Original Moves will show up on the Cardists
    profile.
    """
    # users can submit moves that were created by other Cardists.
    original = models.BooleanField(default=False)

    def __unicode__(self):
        return "{}".format(self.name)


class Video(Named, HasAUser, Likeable, Descriptable, DateCreatedAndUpdate):
    """
    Parent Class of SingleMovePerformance and MultiMovePerformance.
    """
    class Meta:
        abstract, ordering = True, ("-id",)
    private = models.BooleanField(default=False)
    youtube_link = models.CharField(
        max_length=1000, blank=True, null=True, unique=True)
    instagram_link = models.CharField(
        max_length=1000, blank=True, null=True, unique=True)
    comments = models.ManyToManyField("Comment")
    placeholder_image = models.FileField(upload_to='uploads/placeholders/',
        null=True, blank=True)


class ClassicMovePerformance(Video):
    """
    Cardistry Performance Video of a single ClassicMove.
    """
    move = models.ForeignKey("ClassicMove", null=True)


class UserMovePerformance(Video):
    """
    Cardistry Performance Video of a single User Defined Move.
    """
    move = models.ForeignKey("UserMove", null=True) # should these move fields be null????


class MultiMovePerformance(Video):
    """
    Cardistry Video of (multiple) performances of multiple Moves.
    """
    user_moves = models.ManyToManyField("UserMove")
    classic_moves = models.ManyToManyField("ClassicMove")


class Comment(Likeable, HasAUser, DateCreatedAndUpdate):
    """
    Comment on a Video, can comment on a comment.
    """
    class Meta:
        ordering = ("-date_created",)
    text = models.TextField()
    comments = models.ManyToManyField("self")


class Rank(Named, DateCreatedAndUpdate, Descriptable):
    class Meta:
        ordering = ("-id",)


class Privilege(DateCreatedAndUpdate):
    pass


class Profile(HasAUser, DateCreatedAndUpdate, Descriptable, Likeable):
    """
    Cardist's Profile
    """
    class Meta:
        ordering = ("-first_name",)
    rank = models.CharField(max_length=50)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    # I want this to be comma seperated names
    # that potentially link to other cardist's
    # profiles if they exist.
    inspiration = models.TextField()
    url = models.CharField(max_length=500)
    # not sure how to implement fav classic move
    # maybe foreign key to classicmove model
    # maybe just a charfield
    # favorite_classic_move = models.

got_moves-api/templates/moves/add_classic.html
{% extends 'base.html' %}
{% block body %}
<form class="classic_form_element" action="{% url 'post_classic_move' %}" \
    method="POST" onsubmit="return video_form_submit()" enctype="multipart/form-data">
    <div class="form_header">Create a New Classic Move</div>
    {% csrf_token %}
    <div class="classic_form_field">
        <label class="classic_form_label" for="name">Name: </label>
        <span class="classic_name_error_span"></span>
        <input class="form_text_input classic_form_input classic_name_text_input" type="text" name="name" \
            placeholder="Name">
    </div>
    <div class="classic_form_field">
        <label class="classic_form_label" for="youtube_link">YouTube Link: </label>
        <input class="form_text_input classic_form_input youtube_link_text_input" type="text" name="youtube_link" \
            placeholder="Copy/Paste a YouTube link">
    </div>
    <div class="classic_form_field">
        <label class="classic_form_label" for="description">Description: </label>
        <input class="form_text_input classic_form_input " type="text" name="description" \
            placeholder="Short sentence describing the Move.">
    </div>
    <div class="classic_form_field">
        <label class="classic_form_label" for="placeholder_image">Placeholder Image: </label>
        <input id="id_placeholder_image" name="placeholder_image" type="file" />
    </div>
    <div class="classic_form_field">
        <label class="classic_form_label" for="credits">Credits: </label>
        <input class="form_text_input classic_form_input " type="text" name="credits" \
            placeholder="Who inspired this move?">
    </div>
    <div class="classic_form_field">
        <label class="classic_form_label" for="estimated_creation_date">Estimated Creation Date: </label>
        <input class="classic_form_input " type="date" name="estimated_creation_date" \
            placeholder="estimated_creation_date">
    </div>
    <div class="classic_form_field">
        <label class="classic_form_label" for="category">Category: </label>
        <select class="classic_form_select" name="" onchange="choose_number_of_hands()">
            <option value="two_handed">Two Handed</option>
            <option value="one_handed">One Handed</option>
        </select>
        <select class="classic_form_select categories_select" name="category_name">
            {% for category_name in category_names %}
            <option value="{{ category_name }}">{{ category_name }}</option>
            {% endfor %}
        </select>
        <input class="number_of_hands_hidden" type="hidden" \
            name="one_handed" value="">
    </div>
    <input type="submit" value="Submit" class="form_submit_btn classic_form_submit_btn">
</form>
<script type="text/javascript">

</script>
{% endblock body %}

got_moves-api/templates/moves/categories.html
{% extends 'base.html' %}
{% block body %}
<div class="">
    <div class="">
        <form class="" action="{% url 'create_category' %}" method="POST">
            {% csrf_token %}
            <div class="">
                <label for="name"></label>
                <input class="" type="text" name="name" placeholder="Name">
            </div>
            <input type="submit" value="Submit">
        </form>
    </div>
    <div class="">
        {% for category in categories %}
        <p>{{category.name}}</p>
        {% endfor %}
    </div>
</div>
{% endblock body %}
{% block javascript %}
<script type="text/javascript">
    var body = document.getElementsByTagName('body');
    console.log(body);
</script>
{% endblock javascript %}

got_moves-api/templates/moves/classics.html
{% extends 'base.html' %}
{% block body %}
<form class="" action="" method="POST">
    <div class="">
        <label for="name"></label>
        <input class="" type="text" name="name" placeholder="Name">
    </div>
    <div class="">
        <label for="youtube_link"></label>
        <input class="" type="text" name="youtube_link" placeholder="youtube_link">
    </div>
    <div class="">
        <label for="description"></label>
        <input class="" type="text" name="description" placeholder="description">
    </div>
    <div class="">
        <label for="placeholder_image"></label>
        <input class="" type="text" name="placeholder_image" placeholder="placeholder_image">
    </div>
    <div class="">
        <label for="credits"></label>
        <input class="" type="text" name="credits" placeholder="credits">
    </div>
    <div class="">
        <label for="estimated_creation_date"></label>
        <input class="" type="text" name="estimated_creation_date" placeholder="estimated_creation_date">
    </div>
    <div class="">
        <label for="category"></label>
        <input class="" type="text" name="category" placeholder="category">
    </div>
    <input type="submit" value="Submit">
</form>
<div class="">
    {% for classic in classics %}
    <p>
        <div class="">{{ classic.name }}</div>
        <div class="">{{ classic.description }}</div>
        <div class="">{{ classic.credits }}</div>
    </p>
    {% endfor %}
</div>
{% endblock body %}

got_moves-api/templates/moves/search_classics.html
{% extends 'base.html' %}
{% block body %}
<form class="classic_search_form_element" action="" method="POST">
    <div class="classic_search_field">
        <label class="classic_search_label" for="name"></label>
        <input class="form_text_input classic_search_text_input" type="text" name="search" placeholder="Search for Card Flourishes.">
    </div>
    <input type="submit" value="Submit" class="classic_search_submit_btn">
</form>
{% for classic in classics %}
<!-- <div class="">
    <div class="">{{ classic.name }}</div>
    <div class=""><a href="{% url 'delete_classic' id=classic.id %}">delete</a></div>
    <iframe width="215" height="215" src="https://www.youtube.com/embed/{{ classic.youtube_link }}" frameborder="0" allowfullscreen></iframe>
</div> -->
{% endfor %}
{% endblock body %}